app = "vet-prescription-db"
primary_region = "cdg"

[build]
  image = "mongo:8.0"

[env]
  MONGO_INITDB_DATABASE = "vet_prescription"

[[mounts]]
  source = "mongo_data"
  destination = "/data/db"

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
